### ISSUE TITLE
User sees beds vs boats highlighted graphically in the capacity chart

### ISSUE THREAD

**Issue by hartsick** [codeforamerica/jail-dashboard#25]
_From @graysonwright on November 30, 2016 21:54_

First pass: different colored bars

Beds & boats icons to potentially come later

_Copied from original issue: codeforamerica/jail-dashboard-project#132_

**Comment by jennifermarie** [comment]
Use CSS here. Split pop bar into 2; up to size of soft cap has background of beds, past that has background of boats, don't display 2nd bar if not past soft cap.

**Comment by jennifermarie** [comment]
Also: add name indicators on ticks (i.e. soft cap, red zone start) rather than just numbers
