### ISSUE TITLE
Copy changes for clarity

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/jail-dashboard#54]
Make the following edits on pages#home for clarity (based on Jenny's feedback):
- People Summary --> Demographics Summary
- Processing Status --> Case Status
- (Charge Categories) 
  - Violation --> Technical Violation
  - Non-Criminal --> Other (Hold)
  - Ordinance --> Civil Violation

**Comment by jennifermarie** [comment]
Charge category fixes should happen in sample data, not directly in views.

**Comment by hartsick** [comment]
For sample data, should make sure to update both the CSVs and generate tasks for now
